spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fg
    username: sa
    password: sa
    driver-class-name: com.mysql.cj.jdbc.Driver
    jndi-name: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
