version: '3'

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: efgs-federation-gateway-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=fg
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=fg_adm
      - MYSQL_PASSWORD=admin
    networks:
      persistence:
        aliases:
          - mysql

  pgsql:
    image: postgres
    ports:
      - "3306:5432"
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=fg

  backend:
    build: .
    image: efgs-federation-gateway/backend
    container_name: efgs-federation-gateway-backend
    volumes:
      - ./certs:/ec/prod/app/san/efgs
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fg
      - SPRING_DATASOURCE_USERNAME=fg_adm
      - SPRING_DATASOURCE_PASSWORD=admin
      - efgs_dbencryption_password=aaaaaaaaaaaaaaaa
    depends_on:
      - mysql
    networks:
      backend:
      persistence:

networks:
  persistence:
  backend:
